/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Tweet;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adrianmorenomonterde
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuEstadisticas = new javax.swing.JMenu();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación AGI");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROYECTO ALMACENAMIENTO Y GESTIÓN DE LA INFORMACIÓN");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Adrián Moreno Monterde y Pablo Cordón Hidalgo ©");

        jMenuEstadisticas.setText("Estadísticas");
        jMenuBar1.add(jMenuEstadisticas);

        jMenuConsultas.setText("Consultas");
        jMenuBar1.add(jMenuConsultas);

        jMenuSalir.setText("Salir");

        jMenuItemSalir.setText("Salir de la Aplicación");
        jMenuItemSalir.setActionCommand("CerrarVentanaPrincipal");
        jMenuSalir.add(jMenuItemSalir);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(636, 636, 636)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*//Se sobrescribe el método isCellEditable para hacer que las filas no se puedan editar al hacer doble click
    public DefaultTableModel modeloTablaTweets = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            return false; 
        }
    };
    
    //Ejemplo de función para "dibujar" una tabla
    public void dibujarTablaTweets(VistaPrincipal vPrincipal)
    {
        vPrincipal.jTableTweets.setModel(modeloTablaTweets);
        
        String[] columnasTabla = {"id","username", "followers", "text", "language", "date"};
        modeloTablaTweets.setColumnIdentifiers(columnasTabla);
        
        //Para no permitir el redimensionamiento de las columnas con el ratón
        vPrincipal.jTableTweets.getTableHeader().setResizingAllowed(false);
        vPrincipal.jTableTweets.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        
        //Así se fija el ancho de las columnas
        vPrincipal.jTableTweets.getColumnModel().getColumn(0).setPreferredWidth(80);
        vPrincipal.jTableTweets.getColumnModel().getColumn(1).setPreferredWidth(50);
        vPrincipal.jTableTweets.getColumnModel().getColumn(2).setPreferredWidth(20);
        vPrincipal.jTableTweets.getColumnModel().getColumn(3).setPreferredWidth(520);
        vPrincipal.jTableTweets.getColumnModel().getColumn(4).setPreferredWidth(10);
        vPrincipal.jTableTweets.getColumnModel().getColumn(5).setPreferredWidth(100);
    }
    
    //Ejemplo de función para mostrar los datos de la tabla MONITOR a partir de una lista de tweets
    public void rellenarTablaTweets(ArrayList<Tweet> tweets)
    {
        Object[] fila = new Object[6];
        int numRegistros = tweets.size();
        
        for(int i=0; i<numRegistros; i++)
        {
            fila[0] = tweets.get(i).getId();
            fila[1] = tweets.get(i).getUsername();
            fila[2] = tweets.get(i).getFollowers();
            fila[3] = tweets.get(i).getText();
            fila[4] = tweets.get(i).getLanguage();
            fila[5] = tweets.get(i).getDate();
            
            modeloTablaTweets.addRow(fila);
        }
    }
    
    //Ejemplo de función para vaciar el contenido de la tabla TWEET
    public void vaciarTablaTweets()
    {
        while(modeloTablaTweets.getRowCount() > 0)
        {
            modeloTablaTweets.removeRow(0);
        }
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu jMenuConsultas;
    public javax.swing.JMenu jMenuEstadisticas;
    public javax.swing.JMenuItem jMenuItemSalir;
    public javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
