/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author adrianmorenomonterde
 */
public class VistaEstadisticas extends javax.swing.JPanel {

    /**
     * Creates new form VistaEstadisticas
     */
    public VistaEstadisticas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelColeccion = new javax.swing.JLabel();
        jComboBoxColecciones = new javax.swing.JComboBox<>();
        jLabelTweetsAlmacenados = new javax.swing.JLabel();
        jLabelNTweetsAlmacenados = new javax.swing.JLabel();
        jLabelPeriodoDeDescarga = new javax.swing.JLabel();
        jLabelUsuarioConMasSeguidores = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();

        jLabelColeccion.setText("Colección ");

        jComboBoxColecciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Selecciona colección - ", "twitter" }));

        jLabelTweetsAlmacenados.setText("Número de tweets almacenados: ");

        jLabelNTweetsAlmacenados.setText("NTweets");

        jLabelPeriodoDeDescarga.setText("Periodo de descarga: ");

        jLabelUsuarioConMasSeguidores.setText("Usuario con más seguidores: ");

        jLabelUsername.setText("username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelColeccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxColecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTweetsAlmacenados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNTweetsAlmacenados))
                    .addComponent(jLabelPeriodoDeDescarga)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUsuarioConMasSeguidores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUsername)))
                .addContainerGap(622, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelColeccion)
                    .addComponent(jComboBoxColecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTweetsAlmacenados)
                    .addComponent(jLabelNTweetsAlmacenados))
                .addGap(18, 18, 18)
                .addComponent(jLabelPeriodoDeDescarga)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuarioConMasSeguidores)
                    .addComponent(jLabelUsername))
                .addContainerGap(587, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> jComboBoxColecciones;
    private javax.swing.JLabel jLabelColeccion;
    public javax.swing.JLabel jLabelNTweetsAlmacenados;
    private javax.swing.JLabel jLabelPeriodoDeDescarga;
    private javax.swing.JLabel jLabelTweetsAlmacenados;
    public javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelUsuarioConMasSeguidores;
    // End of variables declaration//GEN-END:variables
}
