/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Tweet;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adrianmorenomonterde
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTweets = new javax.swing.JTable();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación AGI");

        jTableTweets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTweets);

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.setActionCommand("CerrarVentanaPrincipal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCerrar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                .addComponent(jButtonCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Se sobrescribe el método isCellEditable para hacer que las filas no se puedan editar al hacer doble click
    public DefaultTableModel modeloTablaTweets = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            return false; 
        }
    };
    
    //Ejemplo de función para "dibujar" una tabla
    public void dibujarTablaTweets(VistaPrincipal vPrincipal)
    {
        vPrincipal.jTableTweets.setModel(modeloTablaTweets);
        
        String[] columnasTabla = {"id","username", "followers", "text", "language", "date"};
        modeloTablaTweets.setColumnIdentifiers(columnasTabla);
        
        //Para no permitir el redimensionamiento de las columnas con el ratón
        vPrincipal.jTableTweets.getTableHeader().setResizingAllowed(false);
        vPrincipal.jTableTweets.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        
        //Así se fija el ancho de las columnas
        vPrincipal.jTableTweets.getColumnModel().getColumn(0).setPreferredWidth(240);
        vPrincipal.jTableTweets.getColumnModel().getColumn(1).setPreferredWidth(70);
        vPrincipal.jTableTweets.getColumnModel().getColumn(2).setPreferredWidth(40);
        vPrincipal.jTableTweets.getColumnModel().getColumn(3).setPreferredWidth(240);
        vPrincipal.jTableTweets.getColumnModel().getColumn(4).setPreferredWidth(40);
        vPrincipal.jTableTweets.getColumnModel().getColumn(5).setPreferredWidth(150);
    }
    
    //Ejemplo de función para mostrar los datos de la tabla MONITOR a partir de una lista de tweets
    public void rellenarTablaTweets(ArrayList<Tweet> tweets)
    {
        Object[] fila = new Object[6];
        int numRegistros = tweets.size();
        
        for(int i=0; i<numRegistros; i++)
        {
            fila[0] = tweets.get(i).getId();
            fila[1] = tweets.get(i).getUsername();
            fila[2] = tweets.get(i).getFollowers();
            fila[3] = tweets.get(i).getText();
            fila[4] = tweets.get(i).getLanguage();
            fila[5] = tweets.get(i).getDate();
            
            modeloTablaTweets.addRow(fila);
        }
    }
    
    //Ejemplo de función para vaciar el contenido de la tabla TWEET
    public void vaciarTablaTweets()
    {
        while(modeloTablaTweets.getRowCount() > 0)
        {
            modeloTablaTweets.removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCerrar;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableTweets;
    // End of variables declaration//GEN-END:variables
}
